name: Run Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup upterm session
      uses: lhotari/action-upterm@v1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: initialize environment
      run: make init

    - name: start docker containers
      run: make containers.start
      env:
        DOCKER_COMPOSE_VERSION: 1.29.2
        DOCKER_COMPOSE_FILE: docker-compose.yml

    - name: Run unit tests
      run: make test.unit

    - name: Run integration tests
      run: make test.integration
