name: Run Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    #- name: Setup upterm session
    #  uses: lhotari/action-upterm@v1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: initialize environment
      run: | 
        cp .env.sample .env
        mkdir -p .docker-data/.mongo-data .docker-data/.rabbit-data .docker-data/.rabbit-log .docker-data/.prometheus-data
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: start docker containers
      run: docker compose up -d
      env:
        DOCKER_COMPOSE_VERSION: 1.29.2
        DOCKER_COMPOSE_FILE: docker-compose.yml

    - name: Run unit tests
      run: |
        source venv/bin/activate
        source .env
        python -m unittest discover -s . -p "test_*.py"

    - name: Run integration tests
      run: |
        source venv/bin/activate
        source .env
        export REGION_DB_NAME=neighbor_price_test
        python -m pytest
